<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7QU5CGR" failures="1" tests="6" name="practice_listener.InvoiceTest_RetryListener" time="0.052" errors="0" timestamp="08 May 2024 10:37:56 GMT" skipped="5">
  <testcase classname="practice_listener.InvoiceTest_RetryListener" name="activate_Sim" time="0.008">
    <skipped/>
  </testcase> <!-- activate_Sim -->
  <testcase classname="practice_listener.InvoiceTest_RetryListener" name="activate_Sim" time="0.004">
    <skipped/>
  </testcase> <!-- activate_Sim -->
  <testcase classname="practice_listener.InvoiceTest_RetryListener" name="activate_Sim" time="0.008">
    <failure message="expected [Login] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at practice_listener.InvoiceTest_RetryListener.activate_Sim(InvoiceTest_RetryListener.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- activate_Sim -->
  <testcase classname="practice_listener.InvoiceTest_RetryListener" name="activate_Sim" time="0.022">
    <skipped/>
  </testcase> <!-- activate_Sim -->
  <testcase classname="practice_listener.InvoiceTest_RetryListener" name="activate_Sim" time="0.005">
    <skipped/>
  </testcase> <!-- activate_Sim -->
  <testcase classname="practice_listener.InvoiceTest_RetryListener" name="activate_Sim" time="0.005">
    <skipped/>
  </testcase> <!-- activate_Sim -->
</testsuite> <!-- practice_listener.InvoiceTest_RetryListener -->
